name: Deploy cljs site to github-pages

on:
  push:
    branches: [ cljs ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@5.1
        with:
          lein: 2.9.8

      - name: Compile Clojurescript
        run: lein cljsbuild once min
